version: '3.6'

services:
  web:
    build: ./
    restart: always
    env_file:
        - ./.env
    command: waitress-serve --port=80 rembg.cmd.server:app
    volumes:
      - ./src:/srv:delegated
    ports:
      - 80:80
